import "@/app/globals.css";
import { Logo } from "@/components/Logo";
import Stack from "@/components/Stack";
import Link from "next/link";
import Image from "next/image";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function NavButton({ children, href }: { children: string; href: string }) {
  return (
    <div className="text-gray-100 text p-2  ">
      <Link
        href={`${href}`}
        className="p-2 block  group hover:bg-gray-400/60 w-full text-left rounded-md transition-all duration-200"
      >
        <p className="group-hover:translate-x-2 transition-all duration-200">
          {children}
        </p>
      </Link>
    </div>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="h-screen __next" id="__next">
        <div className="bg-gray-50 h-screen flex flex-col w-full">
          <nav className="h-20 w-full px-8 bg-slate-800 border-b-2 border-slate-900 flex items-center justify-between">
            <Link href="/">
              <Logo className="h-20 w-20" />
            </Link>
            <div>
              <Stack className="text-white gap-6 text-lg" direction="h">
                <Link href="/">Home</Link>
                <Link href="menu">Menu</Link>
                <Link href="/">Contact Us</Link>
              </Stack>
            </div>
          </nav>
          <div className="flex-1 flex">
            <div className="w-72 flex flex-col justify-between bg-slate-800">
              <div className="text-gray-100 text-lg p-4 border-b-2 border-b-slate-900">
                Alley Anchor
              </div>

              <div className="flex-1">
                <NavButton href="/dashboard/inbox">Inbox</NavButton>
                <NavButton href="/dashboard/menu">Menu Items</NavButton>
                <NavButton href="/dashboard/notifications">
                  Notifications
                </NavButton>
                <NavButton href="/dashboard/orders">Orders</NavButton>
                <NavButton href="/dashboard/account">Account</NavButton>
                <NavButton href="/dashboard/account">Support</NavButton>
              </div>
              <button className="h-20 flex items-center gap-6 w-full px-4 border-t border-slate-900">
                <div className="relative h-12 w-12 bg-gray-300 rounded-full overflow-hidden">
                  <Image src="/chef.jpg" fill alt="avatar" />
                </div>
                <p className="font-semibold text-white">Lawrence B.</p>
              </button>
            </div>
            <div className="flex-1 ">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
