import "@/app/globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { Logo } from "@/components/Logo";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { garamond } from "@/components/fonts/fonts";
import { faBars } from "@fortawesome/free-solid-svg-icons";
import Frame from "@/components/Frame";
import NavBar from "@/components/NavBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Frame
        className="h-screen w-full"
        contentClassName="h-screen w-full flex flex-col"
      >
        <NavBar />
        <main className="flex-1">{children}</main>
      </Frame>
    </>
  );
}
